name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy check
      run: cargo clippy --no-deps -- --deny warnings
    - name: Rustdoc checks
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: "--deny warnings"
